project:
  type: website
  render:
    - "*.qmd"
    # - "!cmip6-processing.qmd"
execute:
  freeze: auto  # re-render only when source changes
  cache: true
  
website:
  title: "Rotorua Lake Modelling"
  favicon: www/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: resources.qmd
        text: Resources
      - href: gantt.qmd
        text: GANTT
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Project Overview"
        href: index.qmd
        contents:
          - gantt.qmd
      - section: "Tasks"
        contents:
          - data-request.qmd
          - cmip6-processing.qmd
  page-footer: 
    left: 
      - text: "Rotorua Plan Change 10" 
        href: "https://www.boprc.govt.nz/your-council/plans-and-policies/plans/regional-plans/regional-natural-resources-plan/lake-rotorua-nutrient-management-plan-change-10/"
    right: |
      <a href="https://github.com/tadhg-moore/rotorua-pc10" style="margin-right: 10px;">
        <i class="bi bi-github" style="font-size: 1.3em;"></i>
      </a>
      <a href="https://www.boprc.govt.nz/">
        <img src="www/boprc-logo.png" alt="Bay of Plenty Logo" style="height: 32px; vertical-align: middle;">
      </a>

format:
  html:
    theme: cosmo
    css: www/styles.css
    toc: true
    