project:
  type: website
  render:
    - "*.qmd"
    # - "!cmip6-processing.qmd"

website:
  title: "Rotorua Lake Modelling"
  favicon: www/favicon.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: resources.qmd
        text: Resources
      - href: gantt.qmd
        text: GANTT
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Project Overview"
        href: index.qmd
        contents:
          - gantt.qmd
      - section: "Tasks"
        contents:
          - data-request.qmd
          - cmip6-processing.qmd
  page-footer: 
    left: "Rotorua Plan Change 10" 
    right: 
      - icon: github
        href: https://github.com/tadhg-moore/rotorua-pc10

format:
  html:
    theme: cosmo
    css: www/styles.css
    toc: true
    