project:
  type: website
  render:
    - "*.qmd"
    - "!cmip6-processing.qmd"

website:
  title: "Rotorua Lake Modelling"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: resources.qmd
        text: Resources
      - href: gantt.qmd
        text: GANTT
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Project Overview"
        href: index.qmd
        contents:
          - gantt.qmd
      - section: "Tasks"
        contents:
          - data-request.qmd
          - cmip6-processing.qmd
  page-footer: 
    left: "Copyright 2021, Norah Jones" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    