project:
  type: website

website:
  title: "Rotorua Lake Modelling"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - href: resources.qmd
        text: Resources
      - href: gantt.qmd
        text: GANTT

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    