name: Render and Publish Quarto Website

on:
  push:
    branches: [main]     # or 'master'
  pull_request:
  workflow_dispatch:      # allow manual trigger

permissions:
  contents: write         # needed to publish to GitHub Pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.6.30"     # use latest stable

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name:  Install dependencies
        run:   |
         if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get update
              sudo apt-get install -y libudunits2-dev
         fi

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/renv/cache
            renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install renv
        run: Rscript -e 'install.packages("renv")'

      - name: Restore renv packages
        run: Rscript -e 'renv::restore(prompt = FALSE)'
          
      - name: Render site
        run: quarto render website   # or '.' if your _quarto.yml is in the repo root

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: website
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
